package org.hibernate.accessor.bytecode;

import org.hibernate.accessor.HibernateAccessorFactory;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;

import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Field;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;


/**
 * Functional tests for the bytecode-enhanced accessor inner classes.
 *
 * <p>Verifies that the generated {@code Book$$$__HibernateAccessorValueWriter}
 * and {@code Book$$$__HibernateAccessorValueReader} (and their Author equivalents)
 * can actually set and retrieve field values at runtime — not just that the
 * bytecode structure is correct (that is covered by {@link TestBytecodeEnhancement}).
 *
 * <h3>How it works</h3>
 * <ol>
 *   <li>Read the compiled {@code Book.class} and {@code Author.class} bytecodes
 *       from the test classpath.</li>
 *   <li>Run the two-pass enhancement pipeline
 *       ({@link PersistentFieldCollector} then {@link AccessorWriterClassVisitor})
 *       to generate the inner-class accessor bytecodes.</li>
 *   <li>Load the original entity classes <em>and</em> the generated inner classes
 *       through a single custom {@link ClassLoader} so they share the same runtime
 *       package (required for package-private field access via PUTFIELD/GETFIELD).</li>
 *   <li>Obtain each accessor's singleton {@code INSTANCE}, invoke {@code set()} or
 *       {@code get()}, and assert the field value.</li>
 * </ol>
 *
 * <h3>Stub dependencies</h3>
 * The generated inner classes reference three types in the entity's package:
 * {@link HibernateAccessorValueWriter}, {@link HibernateAccessorValueReader},
 * and {@link HibernateAccessorFactory}. Test stubs for these are provided in this
 * package so the generated bytecode can be loaded without the full Hibernate runtime.
 */
public class TestEnhancedAccessors {

	private static final String BOOK_CLASS = "org.hibernate.accessor.bytecode.Book";
	private static final String AUTHOR_CLASS = "org.hibernate.accessor.bytecode.Author";

	/** Custom ClassLoader that hosts both entity classes and generated inner classes. */
	private static ClassLoader enhancedCl;
	/** Book class loaded through {@link #enhancedCl}. */
	private static Class<?> bookClass;
	/** Author class loaded through {@link #enhancedCl}. */
	private static Class<?> authorClass;

	/**
	 * Enhances Book and Author, then creates a custom ClassLoader that hosts both
	 * the original entity bytecodes and the generated accessor inner classes.
	 *
	 * <p>Entities and inner classes must be loaded by the <em>same</em> ClassLoader
	 * so they belong to the same runtime package — otherwise the JVM would reject
	 * the PUTFIELD/GETFIELD instructions on package-private entity fields.
	 * Everything else (JDK types, test stubs, ASM, JUnit) delegates to the parent.
	 */
	@BeforeAll
	static void setup() throws Exception {
		// Clear caches to ensure test isolation across re-runs in the same JVM
		HibernateAccessorFactory.writerCache.clear();
		HibernateAccessorFactory.readerCache.clear();

		// Read original entity bytecodes from the test classpath
		Map<String, byte[]> classMap = new HashMap<>();
		classMap.put( BOOK_CLASS, readClassBytes( BOOK_CLASS ) );
		classMap.put( AUTHOR_CLASS, readClassBytes( AUTHOR_CLASS ) );

		// Run the two-pass enhancement and collect generated inner class bytecodes
		enhanceAndCollect( BOOK_CLASS, classMap );
		enhanceAndCollect( AUTHOR_CLASS, classMap );

		// Custom ClassLoader: defines entity + inner classes from classMap,
		// delegates everything else to the parent (test) ClassLoader
		enhancedCl = new ClassLoader( TestEnhancedAccessors.class.getClassLoader() ) {
			@Override
			protected Class<?> loadClass(String name, boolean resolve) throws ClassNotFoundException {
				synchronized ( getClassLoadingLock( name ) ) {
					Class<?> c = findLoadedClass( name );
					if ( c != null ) {
						return c;
					}
					byte[] bytes = classMap.get( name );
					if ( bytes != null ) {
						c = defineClass( name, bytes, 0, bytes.length );
						if ( resolve ) {
							resolveClass( c );
						}
						return c;
					}
					return super.loadClass( name, resolve );
				}
			}
		};

		// Pre-load entity classes so they are available for all test methods
		bookClass = enhancedCl.loadClass( BOOK_CLASS );
		authorClass = enhancedCl.loadClass( AUTHOR_CLASS );
	}

	/** Reads the raw .class bytes for the given fully-qualified class name from the test classpath. */
	private static byte[] readClassBytes(String className) throws IOException {
		String path = className.replace( '.', '/' ) + ".class";
		try ( InputStream is = TestEnhancedAccessors.class.getClassLoader().getResourceAsStream( path ) ) {
			return is.readAllBytes();
		}
	}

	/**
	 * Runs the two-pass enhancement pipeline on the given class and adds every
	 * generated inner class (writers + readers) to {@code classMap}.
	 *
	 * <p>Pass 1 ({@link PersistentFieldCollector}): identifies JPA-annotated fields.
	 * <br>Pass 2 ({@link AccessorWriterClassVisitor}): generates accessor inner classes.
	 */
	private static void enhanceAndCollect(String className, Map<String, byte[]> classMap) throws IOException {
		byte[] originalBytes = classMap.get( className );

		// Pass 1 — collect persistent field metadata
		ClassReader reader = new ClassReader( originalBytes );
		PersistentFieldCollector collector = new PersistentFieldCollector();
		reader.accept( collector, 0 );

		// Pass 2 — generate writer and reader inner classes for each persistent field
		ClassWriter writer = new ClassWriter( reader, 0 );
		AccessorWriterClassVisitor enhancer = new AccessorWriterClassVisitor(
				writer, collector.getPersistentFields()
		);
		reader.accept( enhancer, 0 );

		// Store generated inner class bytecodes keyed by binary name
		for ( AccessorWriterClassVisitor.InnerClassInfo info : enhancer.getInnerClasses() ) {
			classMap.put( info.getClassName().replace( '/', '.' ), info.getBytecode() );
		}
	}

	/**
	 * Loads the given accessor class through the enhanced ClassLoader and returns
	 * its singleton {@code INSTANCE}. The first call for a given class triggers
	 * class loading, which runs the static initializer and registers the instance
	 * in {@link HibernateAccessorFactory#writerCache} or
	 * {@link HibernateAccessorFactory#readerCache}.
	 */
	private static Object getAccessorInstance(String className) throws Exception {
		Class<?> clazz = enhancedCl.loadClass( className );
		return clazz.getField( "INSTANCE" ).get( null );
	}

	/** Creates a Book instance via the enhanced ClassLoader's public 3-arg constructor. */
	private static Object newBook(String isbn, String title, String text) throws Exception {
		return bookClass.getConstructor( String.class, String.class, String.class )
				.newInstance( isbn, title, text );
	}

	/** Creates an Author instance via the enhanced ClassLoader's default constructor. */
	private static Object newAuthor() throws Exception {
		return authorClass.getDeclaredConstructor().newInstance();
	}

	/** Reads a (possibly package-private) field value from an entity instance via reflection. */
	private static Object getField(Object obj, String fieldName) throws Exception {
		Field f = obj.getClass().getDeclaredField( fieldName );
		f.setAccessible( true );
		return f.get( obj );
	}

	/** Sets a (possibly package-private) field value on an entity instance via reflection. */
	private static void setField(Object obj, String fieldName, Object value) throws Exception {
		Field f = obj.getClass().getDeclaredField( fieldName );
		f.setAccessible( true );
		f.set( obj, value );
	}

	/** Invokes the accessor writer's {@code set(Object target, Object value)} method. */
	private static void invokeSet(Object accessor, Object target, Object value) throws Exception {
		accessor.getClass()
				.getMethod( "set", Object.class, Object.class )
				.invoke( accessor, target, value );
	}

	/** Invokes the accessor reader's {@code get(Object target)} method. */
	private static Object invokeGet(Object accessor, Object target) throws Exception {
		return accessor.getClass()
				.getMethod( "get", Object.class )
				.invoke( accessor, target );
	}

	// ---- Book Writer tests ----
	// Verify that calling set() on the generated HibernateAccessorValueWriter
	// inner class actually assigns the value to the corresponding entity field.

	@Test
	void bookWriterSetsIsbn() throws Exception {
		Object book = newBook( "000", "t", "x" );
		Object writer = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Book__isbn" );

		invokeSet( writer, book, "978-0-321" );

		assertEquals( "978-0-321", getField( book, "isbn" ) );
	}

	@Test
	void bookWriterSetsTitle() throws Exception {
		Object book = newBook( "000", "old", "x" );
		Object writer = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Book__title" );

		invokeSet( writer, book, "Hibernate in Action" );

		assertEquals( "Hibernate in Action", getField( book, "title" ) );
	}

	@Test
	void bookWriterSetsText() throws Exception {
		Object book = newBook( "000", "t", "old" );
		Object writer = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Book__text" );

		invokeSet( writer, book, "new content" );

		assertEquals( "new content", getField( book, "text" ) );
	}

	@Test
	void bookWriterSetsPublicationDate() throws Exception {
		Object book = newBook( "000", "t", "x" );
		Object writer = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Book__publicationDate" );
		LocalDate date = LocalDate.of( 2024, 1, 15 );

		invokeSet( writer, book, date );

		assertEquals( date, getField( book, "publicationDate" ) );
	}

	@Test
	void bookWriterSetsAuthors() throws Exception {
		Object book = newBook( "000", "t", "x" );
		Object writer = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Book__authors" );
		Set<Object> authors = new HashSet<>();

		invokeSet( writer, book, authors );

		assertEquals( authors, getField( book, "authors" ) );
	}

	// ---- Book Reader tests ----
	// Verify that calling get() on the generated HibernateAccessorValueReader
	// inner class returns the current value of the corresponding entity field.

	@Test
	void bookReaderGetsIsbn() throws Exception {
		Object book = newBook( "978-0-321", "t", "x" );
		Object reader = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Book__isbn" );

		assertEquals( "978-0-321", invokeGet( reader, book ) );
	}

	@Test
	void bookReaderGetsTitle() throws Exception {
		Object book = newBook( "000", "Hibernate Guide", "x" );
		Object reader = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Book__title" );

		assertEquals( "Hibernate Guide", invokeGet( reader, book ) );
	}

	@Test
	void bookReaderGetsText() throws Exception {
		Object book = newBook( "000", "t", "chapter one" );
		Object reader = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Book__text" );

		assertEquals( "chapter one", invokeGet( reader, book ) );
	}

	@Test
	void bookReaderGetsPublicationDate() throws Exception {
		Object book = newBook( "000", "t", "x" );
		LocalDate date = LocalDate.of( 2024, 6, 1 );
		setField( book, "publicationDate", date );

		Object reader = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Book__publicationDate" );

		assertEquals( date, invokeGet( reader, book ) );
	}

	@Test
	void bookReaderGetsAuthors() throws Exception {
		Object book = newBook( "000", "t", "x" );
		Set<Object> authors = new HashSet<>();
		setField( book, "authors", authors );

		Object reader = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Book__authors" );

		assertEquals( authors, invokeGet( reader, book ) );
	}

	@Test
	void bookReaderReturnsNullForUnsetField() throws Exception {
		Object book = newBook( "000", "t", "x" );

		Object reader = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Book__publicationDate" );

		assertNull( invokeGet( reader, book ) );
	}

	// ---- Author Writer tests ----
	// Same writer verification for the Author entity (id and books fields).

	@Test
	void authorWriterSetsId() throws Exception {
		Object author = newAuthor();
		Object writer = getAccessorInstance(
				AUTHOR_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Author__id" );

		invokeSet( writer, author, 42L );

		assertEquals( 42L, getField( author, "id" ) );
	}

	@Test
	void authorWriterSetsBooks() throws Exception {
		Object author = newAuthor();
		Object writer = getAccessorInstance(
				AUTHOR_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Author__books" );
		Set<Object> books = new HashSet<>();

		invokeSet( writer, author, books );

		assertEquals( books, getField( author, "books" ) );
	}

	// ---- Author Reader tests ----
	// Same reader verification for the Author entity (id and books fields).

	@Test
	void authorReaderGetsId() throws Exception {
		Object author = newAuthor();
		setField( author, "id", 99L );

		Object reader = getAccessorInstance(
				AUTHOR_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Author__id" );

		assertEquals( 99L, invokeGet( reader, author ) );
	}

	@Test
	void authorReaderGetsBooks() throws Exception {
		Object author = newAuthor();
		Set<Object> books = new HashSet<>();
		setField( author, "books", books );

		Object reader = getAccessorInstance(
				AUTHOR_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Author__books" );

		assertEquals( books, invokeGet( reader, author ) );
	}

	// ---- Round-trip tests ----
	// End-to-end: write a value through the writer, then read it back through
	// the reader and verify they agree — confirms the full set-then-get cycle.

	@Test
	void bookWriterAndReaderRoundTrip() throws Exception {
		Object book = newBook( "000", "t", "x" );

		Object writer = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Book__isbn" );
		Object reader = getAccessorInstance(
				BOOK_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Book__isbn" );

		invokeSet( writer, book, "978-1-234" );

		assertEquals( "978-1-234", invokeGet( reader, book ) );
	}

	@Test
	void authorWriterAndReaderRoundTrip() throws Exception {
		Object author = newAuthor();

		Object writer = getAccessorInstance(
				AUTHOR_CLASS + AccessorWriterClassVisitor.WRITER_INFIX + "__Author__id" );
		Object reader = getAccessorInstance(
				AUTHOR_CLASS + AccessorWriterClassVisitor.READER_INFIX + "__Author__id" );

		invokeSet( writer, author, 77L );

		assertEquals( 77L, invokeGet( reader, author ) );
	}
}
